# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [98]:
import numpy as np

In [99]:
x = np.random.uniform(0, 20, size = (4, 7))
(x - x.min()) / (x.max() - x.min())

array([[0.34733423, 0.07078552, 0.90317913, 0.18604176, 0.44806446,
        0.71661982, 0.59429277],
       [0.97974413, 0.44268796, 0.6452106 , 0.70619133, 0.        ,
        0.0174254 , 0.05061779],
       [0.5215342 , 0.22066689, 1.        , 0.2637494 , 0.82940612,
        0.87919048, 0.61576567],
       [0.4397622 , 0.48381325, 0.89081995, 0.8619477 , 0.86307428,
        0.94534522, 0.70284945]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [100]:
a = np.random.randint(0, 10, size = (8, 10))
b = np.sum(a, axis=1)
mini = min(b)
ind = np.where(b == mini)
print(a[ind][0])

[5 1 4 5 5 5 6 1 2 1]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [101]:
ings = np.loadtxt("minutes_n_ingredients.csv", dtype="int32", delimiter=',', skiprows=1)
print(ings[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [102]:
np.set_printoptions(suppress=True)
print(np.mean(ings[1:], axis=0))
print(np.min(ings[1:], axis=0))
print(np.max(ings[1:], axis=0))
print(np.median(ings[1:], axis=0))

[222065.27212272  21601.21710217      9.05521055]
[38  0  1]
[    537671 2147483647         39]
[207196.     40.      9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [103]:
q075 = np.quantile(ings[:,1],.75)
ings[:,1] = np.clip(ings[:,1], 0, q075)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [104]:
print(np.sum(ings[:,1] == 0))
ings[:,1] = np.where(ings[:,1] == 0, 1, ings[:,1])
print(np.sum(ings[:,1] == 0))

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [105]:
print(len(np.unique(ings[:,0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [106]:
unique_nings = np.unique(ings[:,2])
print(len(unique_nings))
print(unique_nings)

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [107]:
temp = np.copy(ings)
mask = temp[:,2] <= 5
print(temp[mask])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [108]:
ing_for_minute = np.array(ings[:,2]/ings[:,1])
print(max(ing_for_minute))

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [109]:
temp = np.copy(ings)
temp = temp[temp[:, 1].argsort()]
temp = np.flip(temp, axis=0)[0:100]
print(np.mean(temp[:,2], axis=0))

9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [110]:
print(ings[np.random.randint(0,100000,10)])

[[381923     65     15]
 [295052     65      6]
 [318586     40     16]
 [216638     50      6]
 [  3101     65     10]
 [359449     55     14]
 [ 17783     65      4]
 [ 32742     45     13]
 [310607     14     10]
 [147982     60      3]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [111]:
avg_ings = np.mean(ings[:,2])
sum_avg = np.sum(ings[:,2] < avg_ings)
print(sum_avg/1000)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [112]:
version2 = np.zeros((100000, 4), dtype="int32")
version2[:,:-1] = ings
version2[:,3] = np.where((version2[:,1] <= 20) & (version2[:,2] <= 5), 1, 0)
print(version2)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [113]:
temp = np.copy(version2)
mask = version2[:,3] == 1
print(len(temp[mask]) / len(ings) * 100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [114]:
temp = np.copy(ings)
mask_short = temp[:,1] <= 10
mask_middle = (temp[:,1] > 10) & (temp[:,1] < 20)
mask_long = temp[:,1] >= 20
short = temp[mask_short]
middle = temp[mask_middle]
long = temp[mask_long]
res_size = min(len(short), len(middle), len(long))
res_array = np.array([short[:res_size], middle[:res_size], long[:res_size]])
print(np.shape(res_array))

(3, 7783, 3)
